auth:
  type: DISABLED
kafka:
  clusters:
  - bootstrapServers: broker:29092
    kafkaConnect:
    - address: http://connect:8083
      name: Kafka Connect
    name: BI Kafka
    properties: {}
    readOnly: false
    schemaRegistry: http://schema-registry:8081
rbac:
  roles: []
